export interface Idea {
  id: number;
  name: string;
  slug: string;
  tagline: string;
  description: string;
  category: Category;
  status: Status;
  targetMarket: string;
  tam: string;
  pricing: string;
  stack: string[];
  effort: Effort;
  revenueModel: string;
  tags: string[];
}

export type Category =
  | "ai-departments"
  | "saas"
  | "marketplace"
  | "agency"
  | "content"
  | "vertical"
  | "consumer"
  | "infrastructure"
  | "moonshot";

export type Status = "active" | "vision" | "medium-term" | "longterm" | "brainstorm" | "copy-adapt";
export type Effort = "1-week" | "2-weeks" | "1-month" | "3-months" | "6-months" | "1-year";

export const CATEGORIES: Record<Category, { label: string; color: string }> = {
  "ai-departments": { label: "AI Departments", color: "#6366f1" },
  saas: { label: "SaaS", color: "#06b6d4" },
  marketplace: { label: "Marketplace", color: "#f59e0b" },
  agency: { label: "Agency", color: "#ec4899" },
  content: { label: "Content", color: "#8b5cf6" },
  vertical: { label: "Vertical AI", color: "#10b981" },
  consumer: { label: "Consumer", color: "#f97316" },
  infrastructure: { label: "Infrastructure", color: "#64748b" },
  moonshot: { label: "Moonshot", color: "#ef4444" },
};

export const STATUS_CONFIG: Record<Status, { label: string; color: string; emoji: string }> = {
  active: { label: "Active", color: "#22c55e", emoji: "🟢" },
  vision: { label: "Vision", color: "#6366f1", emoji: "🔮" },
  "medium-term": { label: "Medium-Term", color: "#f59e0b", emoji: "🟡" },
  longterm: { label: "Long-Term", color: "#64748b", emoji: "⏳" },
  brainstorm: { label: "Brainstorm", color: "#94a3b8", emoji: "💡" },
  "copy-adapt": { label: "Copy+Adapt", color: "#06b6d4", emoji: "⚡" },
};

export const IDEAS: Idea[] = [
  {
    id: 1, name: "A-Impact", slug: "a-impact",
    tagline: "AI Departments for DACH SMEs",
    description: "Complete AI departments (Sales, Marketing, Support, Finance, HR, Legal, Ops, IT) for German-speaking mid-market companies. Each department runs 8 autonomous AI agents, replacing entire teams. NVIDIA Inception member, 26 qualified leads.",
    category: "ai-departments", status: "active",
    targetMarket: "3.5M SMEs in DACH region",
    tam: "€50B+ addressable market",
    pricing: "€500-4,000/mo per department, €3,500-25K/mo bundles",
    stack: ["Python", "Claude API", "Voice Agents", "NVIDIA Inception"],
    effort: "6-months", revenueModel: "Monthly SaaS + Setup fees",
    tags: ["b2b", "enterprise", "dach", "ai-agents", "departments"],
  },
  {
    id: 2, name: "Business OS", slug: "business-os",
    tagline: "Build a complete business in 90 seconds",
    description: "Input a business idea, get brand identity, marketing strategy, sales deck, tech stack recommendation, and 6 AI agents — all generated in 90 seconds. 37 API endpoints, generates 13 files per job.",
    category: "saas", status: "active",
    targetMarket: "600K new startups/year in DACH, global founders",
    tam: "€15B startup tools market",
    pricing: "€49 one-time starter, €299/mo pro, €1,500/mo enterprise",
    stack: ["FastAPI", "Next.js 15", "GPT-4o", "37 endpoints"],
    effort: "3-months", revenueModel: "Freemium + subscription + 3% revshare",
    tags: ["founders", "startup", "automation", "no-code"],
  },
  {
    id: 3, name: "MDT (Marketing Dream Team)", slug: "mdt",
    tagline: "40 AI marketing experts in 8 squads",
    description: "Content, Social, SEO, Paid, Email, Analytics, Growth, Brand — each squad has 5 specialized AI agents. 198 task types, n8n webhook integration. Your entire marketing department for a fraction of the cost.",
    category: "ai-departments", status: "active",
    targetMarket: "Companies needing marketing but can't afford full teams",
    tam: "€280B global marketing services",
    pricing: "€299-999/mo SaaS or €5-50 pay-per-task",
    stack: ["FastAPI", "Claude Sonnet 4.6", "n8n", "198 task types"],
    effort: "3-months", revenueModel: "SaaS + pay-per-task",
    tags: ["marketing", "content", "seo", "social", "email"],
  },
  {
    id: 4, name: "Proposal Agent", slug: "proposal-agent",
    tagline: "Perfect B2B proposals in seconds from a 30-sec voice brief",
    description: "Record a 30-second voice memo about the deal. AI generates a professional, personalized sales proposal with pricing, timeline, scope, and competitive positioning. 3 industry-specific templates.",
    category: "saas", status: "vision",
    targetMarket: "500M+ B2B sales professionals globally",
    tam: "€8B sales enablement market",
    pricing: "€1-2 per proposal or €29/mo unlimited, €499/mo white-label",
    stack: ["FastAPI", "Whisper", "GPT-4o", "PDF generation"],
    effort: "1-month", revenueModel: "Pay-per-use + subscription",
    tags: ["sales", "b2b", "voice", "proposals", "automation"],
  },
  {
    id: 5, name: "AI Departments (Enterprise)", slug: "ai-departments-enterprise",
    tagline: "Plug-and-play AI departments that replace entire teams",
    description: "Full autonomous departments running 24/7. Each department handles all processes end-to-end: hiring, onboarding, performance tracking, reporting. DSGVO-compliant, multi-language.",
    category: "ai-departments", status: "vision",
    targetMarket: "Enterprise firms >10 employees",
    tam: "€280B BPO market",
    pricing: "€1,500-4,000/mo per dept, €15-25K/mo full stack, €5-15K setup",
    stack: ["Multi-agent systems", "Workflow automation", "DSGVO"],
    effort: "6-months", revenueModel: "Monthly retainer + setup",
    tags: ["enterprise", "bpo", "automation", "departments"],
  },
  {
    id: 6, name: "AI Company Builder", slug: "ai-company-builder",
    tagline: "A factory that builds 1-10 specialized AI companies per year",
    description: "Reusable playbook to spin up vertical AI companies (Law, Medicine, Insurance, Real Estate). Each company targets a specific industry with proven tech architecture. Portfolio approach with 80-100% equity hold.",
    category: "infrastructure", status: "vision",
    targetMarket: "VCs, accelerators, serial entrepreneurs",
    tam: "€500B+ across verticals",
    pricing: "Equity hold + €99-999/mo SaaS per vertical",
    stack: ["Transferable architecture", "Industry playbooks"],
    effort: "1-year", revenueModel: "Equity + SaaS revenue per company",
    tags: ["venture", "portfolio", "yc", "verticals", "scaling"],
  },
  {
    id: 7, name: "Dominika JV", slug: "dominika-jv",
    tagline: "Joint venture: Sales + Customer Service AI army",
    description: "Partner with an established firm. Deploy AI sales and customer service agents that run alongside their existing team. Performance-based pricing with monthly reports and optimization.",
    category: "agency", status: "medium-term",
    targetMarket: "Established businesses wanting AI agents",
    tam: "Custom per partner",
    pricing: "€10-25K setup + €3-5K/mo retainer + performance bonus",
    stack: ["AI Sales agents", "CS agents", "Monitoring dashboard"],
    effort: "3-months", revenueModel: "Setup + retainer + performance %",
    tags: ["jv", "partnership", "sales", "customer-service"],
  },
  {
    id: 8, name: "CRM x AI", slug: "crm-ai",
    tagline: "The CRM that runs itself",
    description: "Self-serving CRM that auto-qualifies leads, scores them, generates personalized outreach, books meetings, and closes deals. Colony platform is the prototype. 100 free leads to start.",
    category: "saas", status: "vision",
    targetMarket: "SaaS/Sales teams tired of manual CRM work",
    tam: "€80B CRM market",
    pricing: "€49-299/mo per seat, €999/mo enterprise",
    stack: ["Next.js", "Prisma", "Neon PostgreSQL", "Claude API"],
    effort: "3-months", revenueModel: "Per-seat subscription",
    tags: ["crm", "sales", "leads", "automation", "colony"],
  },
  {
    id: 9, name: "Callcenter AI", slug: "callcenter-ai",
    tagline: "Cloud AI callcenter — no humans, franchise-ready",
    description: "AI voice agents handle inbound and outbound calls. Multilingual, no hardware needed, franchise model available. White-label for existing callcenters wanting to upgrade.",
    category: "vertical", status: "medium-term",
    targetMarket: "BPO/Callcenter market, existing callcenters",
    tam: "€400B global callcenter market",
    pricing: "€500-1,500/mo per agent-slot, €0.10-0.30/min, €25K franchise",
    stack: ["Cloud voice", "Multilingual TTS/STT", "Franchise platform"],
    effort: "6-months", revenueModel: "Per-agent subscription + per-minute + franchise",
    tags: ["voice", "callcenter", "franchise", "multilingual"],
  },
  {
    id: 10, name: "Hotel AI", slug: "hotel-ai",
    tagline: "AI for 50+ hotel processes",
    description: "Check-in, concierge, booking optimization, upselling, review management, housekeeping scheduling. Saves hotels 15-25% of Booking.com commissions by driving direct bookings.",
    category: "vertical", status: "medium-term",
    targetMarket: "700K+ hotels globally, hospitality chains",
    tam: "€30B hotel tech market",
    pricing: "€499-2,999/mo + 5% commission on AI-driven direct bookings",
    stack: ["AI voice/app", "Multilingual", "PMS integration"],
    effort: "6-months", revenueModel: "SaaS + commission",
    tags: ["hospitality", "hotels", "booking", "voice"],
  },
  {
    id: 11, name: "AI Agency + Nigeria", slug: "agency-nigeria",
    tagline: "Marketing agency with cheap execution via Nigeria team",
    description: "AI-guided strategy with cost-effective Nigerian execution team. Combine with Skool community for recurring membership revenue. Agency retainer + community model.",
    category: "agency", status: "medium-term",
    targetMarket: "SMEs wanting marketing services",
    tam: "€100B+ marketing agency market",
    pricing: "€500-2K/mo agency retainer, €49-99/mo community",
    stack: ["Skool platform", "AI strategy", "Nigeria team"],
    effort: "1-month", revenueModel: "Retainer + membership",
    tags: ["agency", "community", "marketing", "outsourcing"],
  },
  {
    id: 12, name: "ECom KI", slug: "ecom-ki",
    tagline: "AI for Amazon FBA sellers",
    description: "Product research, listing optimization, PPC automation, supplier management, review monitoring. Helium10 alternative powered by AI agents that actually execute, not just suggest.",
    category: "vertical", status: "medium-term",
    targetMarket: "500K+ active Amazon FBA sellers",
    tam: "€5B Amazon seller tools market",
    pricing: "€99-499/mo or 2% commission on optimized sales",
    stack: ["AI agents", "Amazon API", "PPC automation"],
    effort: "3-months", revenueModel: "SaaS + commission",
    tags: ["ecommerce", "amazon", "fba", "ppc"],
  },
  {
    id: 13, name: "Lovable 10x", slug: "lovable-10x",
    tagline: "App builder that ACTUALLY deploys",
    description: "Unlike other AI app builders that generate broken code, this one generates → tests → fixes → deploys → monitors. Your app goes live in minutes, not days. Based on BOS architecture.",
    category: "saas", status: "medium-term",
    targetMarket: "No-code users, non-developers",
    tam: "€15B no-code/low-code market",
    pricing: "Free (1 app), €29/mo (5 apps), €99/mo (unlimited)",
    stack: ["AI code gen", "Testing pipeline", "Auto-deploy", "Monitoring"],
    effort: "3-months", revenueModel: "Freemium + subscription",
    tags: ["no-code", "app-builder", "deployment", "automation"],
  },
  {
    id: 14, name: "Law Firms AI", slug: "law-firms-ai",
    tagline: "Legal work at €50/hr instead of €300",
    description: "AI generates contracts, compliance checks, legal letters, deadline management. Template-based with German law rules. Partnership model with actual lawyers for review.",
    category: "vertical", status: "medium-term",
    targetMarket: "Small firms, freelancers, individuals",
    tam: "€15B German legal services market",
    pricing: "€5-50/document, €29/mo individuals, €199/mo business",
    stack: ["AI agents", "Legal templates", "DSGVO-compliant"],
    effort: "3-months", revenueModel: "Pay-per-document + subscription",
    tags: ["legal", "contracts", "compliance", "dach"],
  },
  {
    id: 15, name: "AI Dating Agent", slug: "ai-dating-agent",
    tagline: "Your agent finds, texts, and books dates for you",
    description: "AI swipes, matches, and carries conversations on dating apps. Learns your preferences, qualifies matches by interests and values, then books the date. You just show up.",
    category: "consumer", status: "longterm",
    targetMarket: "Dating app users (swipe fatigue)",
    tam: "€10B dating app market",
    pricing: "€5/50 outreaches, €19/mo basic, €49/mo premium, €99/mo concierge",
    stack: ["Multi-platform", "Voice agents", "Personality memory"],
    effort: "6-months", revenueModel: "Credits + subscription",
    tags: ["dating", "consumer", "ai-agent", "matching"],
  },
  {
    id: 16, name: "AI Companion", slug: "ai-companion",
    tagline: "Daily AI life coach with persistent memory",
    description: "Morning check-ins, CBT/ACT techniques, pattern recognition, habit tracking. Remembers your history, adapts coaching style, escalates to human therapist if needed.",
    category: "consumer", status: "longterm",
    targetMarket: "Mental health app users, Gen Z/millennial",
    tam: "€7B mental health app market (20% CAGR)",
    pricing: "Free (1 check-in/day), €9/mo unlimited, €29/mo coaching plans",
    stack: ["Persistent memory", "Voice-based", "CBT/ACT/MI"],
    effort: "6-months", revenueModel: "Freemium + subscription",
    tags: ["mental-health", "coaching", "consumer", "voice"],
  },
  {
    id: 17, name: "IQ/Test Platform", slug: "iq-test-platform",
    tagline: "Gamified IQ, MBTI, EQ tests — shareable and social",
    description: "Take curated personality and intelligence tests. Get AI-generated deep results. Share on social media. Viral loop built in. Inspiration: 16personalities (100M+ visits/mo).",
    category: "consumer", status: "longterm",
    targetMarket: "Test-takers, recruiters, content consumers",
    tam: "€2B personality testing market",
    pricing: "Free (1 test), €4.99 detailed results, €9/mo all tests, €299/mo B2B",
    stack: ["AI result generation", "Gamification", "Social sharing"],
    effort: "1-month", revenueModel: "Freemium + B2B licensing",
    tags: ["consumer", "viral", "testing", "gamification"],
  },
  {
    id: 18, name: "KI Consultant + Verein", slug: "ki-consultant",
    tagline: "Robert as certified AI trainer + association",
    description: "Workshops, certification programs, speaking engagements. Create a German AI education association. Position Robert as the go-to AI implementation expert in DACH.",
    category: "content", status: "longterm",
    targetMarket: "German SMEs, training market",
    tam: "€5B German corporate training market",
    pricing: "€2-5K/day workshops, €499/cert, €99/year association, €1-5K speaking",
    stack: ["Training content", "Certification platform"],
    effort: "6-months", revenueModel: "Workshops + certs + membership + speaking",
    tags: ["education", "consulting", "personal-brand", "dach"],
  },
  {
    id: 19, name: "Books (2 Ideas)", slug: "books",
    tagline: "Autobiography + curated best-of from 100+ books",
    description: "'Journey to AI Empire' autobiography + 'Golden Nuggets' (best insights from 100+ business/tech books, curated and AI-enhanced). Self-publish on Amazon KDP + Audible.",
    category: "content", status: "longterm",
    targetMarket: "Startup founders, AI enthusiasts",
    tam: "€1B business book market",
    pricing: "€9.99-19.99 per book, Audible versions",
    stack: ["Amazon KDP", "Audible", "AI writing assistance"],
    effort: "3-months", revenueModel: "Book sales + speaking leverage",
    tags: ["books", "content", "personal-brand", "publishing"],
  },
  {
    id: 20, name: "Unlimited Energy", slug: "unlimited-energy",
    tagline: "Magnetcoil + steel self-energizing devices",
    description: "Physical energy generation devices using magnetic coils. Off-grid power for consumers. Moonshot concept requiring physics prototyping and materials science expertise.",
    category: "moonshot", status: "longterm",
    targetMarket: "Off-grid enthusiasts, energy independence",
    tam: "€500B+ energy market",
    pricing: "TBD (hardware + licensing)",
    stack: ["Physics prototyping", "Materials science"],
    effort: "1-year", revenueModel: "Hardware sales + licensing",
    tags: ["energy", "hardware", "moonshot", "physics"],
  },
  {
    id: 21, name: "AI Recruiter", slug: "ai-recruiter",
    tagline: "Job profile in, qualified candidates out",
    description: "AI sources candidates, makes screening calls, qualifies them, and books interviews. You just define the role and show up for final interviews.",
    category: "vertical", status: "brainstorm",
    targetMarket: "Hiring managers (€500B+ recruiting market)",
    tam: "€500B recruiting market",
    pricing: "€500-2K pay-per-hire or €299/mo subscription",
    stack: ["AI sourcing", "Voice interviews", "Qualification pipeline"],
    effort: "3-months", revenueModel: "Pay-per-hire + subscription",
    tags: ["recruiting", "hr", "voice", "automation"],
  },
  {
    id: 22, name: "AI Buchhalter", slug: "ai-buchhalter",
    tagline: "Photo invoices → auto-categorized, tax-prepped, DATEV export",
    description: "Snap a photo of any invoice or forward the email. AI categorizes, extracts data, prepares for tax filing, exports to DATEV. Perfect for German freelancers.",
    category: "vertical", status: "brainstorm",
    targetMarket: "4M+ freelancers in DACH + gig workers",
    tam: "€3B accounting software DACH",
    pricing: "€9-49/mo SaaS",
    stack: ["Receipt OCR", "AI categorization", "DATEV integration"],
    effort: "2-weeks", revenueModel: "Monthly subscription",
    tags: ["accounting", "tax", "freelancer", "dach", "datev"],
  },
  {
    id: 23, name: "AI Vertragsmanager", slug: "ai-vertragsmanager",
    tagline: "Upload contracts → AI reads risks, reminds deadlines",
    description: "Upload any contract. AI extracts key terms, warns about risks, tracks deadlines, sends renewal reminders. Never miss a cancellation window again.",
    category: "saas", status: "brainstorm",
    targetMarket: "SMEs, legal teams, freelancers",
    tam: "€5B contract management market",
    pricing: "€19/mo SaaS",
    stack: ["Contract parsing", "Risk detection", "Deadline pipeline"],
    effort: "2-weeks", revenueModel: "Monthly subscription",
    tags: ["legal", "contracts", "automation", "compliance"],
  },
  {
    id: 24, name: "AI Meeting Killer", slug: "ai-meeting-killer",
    tagline: "Async AI reports replace meetings entirely",
    description: "Instead of meetings, AI summarizes updates, asks for decisions async, assigns tasks, and tracks completion. Saves 5-10 hours per week per team.",
    category: "saas", status: "brainstorm",
    targetMarket: "Remote teams, meeting-fatigued companies",
    tam: "€10B team productivity market",
    pricing: "€9/mo per team",
    stack: ["Meeting recording parsing", "Async task assignment"],
    effort: "2-weeks", revenueModel: "Per-team subscription",
    tags: ["productivity", "meetings", "async", "teams"],
  },
  {
    id: 25, name: "AI Ghostwriter", slug: "ai-ghostwriter",
    tagline: "Write books and blogs in YOUR voice",
    description: "Train AI on your writing style, tone, and vocabulary. It writes long-form content that sounds exactly like you. For authors, newsletter writers, and content creators.",
    category: "saas", status: "brainstorm",
    targetMarket: "Authors, newsletter writers, content creators",
    tam: "€5B content creation market",
    pricing: "€29/mo subscription",
    stack: ["Style-trained AI", "Voice cloning for writing"],
    effort: "1-month", revenueModel: "Monthly subscription",
    tags: ["writing", "content", "ghostwriting", "ai-voice"],
  },
  {
    id: 26, name: "AI Immobilien-Scout", slug: "ai-immoscout",
    tagline: "Scans all portals → finds deals, analyzes yield",
    description: "Monitors ImmoScout24, Immowelt, eBay Kleinanzeigen and more. AI calculates yield, compares to market, contacts brokers automatically. For serious real estate investors.",
    category: "vertical", status: "brainstorm",
    targetMarket: "Real estate investors in DACH",
    tam: "€10B proptech market",
    pricing: "€49/mo SaaS",
    stack: ["Web scraping", "Yield analysis", "Outreach automation"],
    effort: "1-month", revenueModel: "Monthly subscription",
    tags: ["real-estate", "investing", "scraping", "dach"],
  },
  {
    id: 27, name: "AI Influencer Manager", slug: "ai-influencer-mgr",
    tagline: "AI manages your social accounts autonomously",
    description: "Posts content, replies to comments, handles DMs, books brand collaborations. Your social media runs on autopilot while you create. Perfect for solo creators.",
    category: "saas", status: "brainstorm",
    targetMarket: "Creators and influencers without team",
    tam: "€20B creator economy",
    pricing: "€49/mo SaaS",
    stack: ["Social posting automation", "DM handling", "Collab booking"],
    effort: "1-month", revenueModel: "Monthly subscription",
    tags: ["influencer", "social-media", "creator", "automation"],
  },
  {
    id: 28, name: "AI Franchise-in-a-Box", slug: "ai-franchise-box",
    tagline: "Complete franchise system powered by AI",
    description: "Operations manual generation, franchisee training, quality assurance, compliance tracking, reporting — all automated. Turn any business into a scalable franchise.",
    category: "infrastructure", status: "brainstorm",
    targetMarket: "Franchisors wanting to systemize",
    tam: "€100B franchise market",
    pricing: "€999/mo white-label SaaS",
    stack: ["Franchise ops automation", "Franchisee portal"],
    effort: "6-months", revenueModel: "Monthly subscription",
    tags: ["franchise", "operations", "white-label", "scaling"],
  },
  {
    id: 29, name: "AI Steuerberater", slug: "ai-steuerberater",
    tagline: "Multi-jurisdiction tax optimization for digital nomads",
    description: "Where should you pay tax? AI analyzes your income sources, residency, and treaties to find the optimal setup. Perfect for digital nomads and expats.",
    category: "vertical", status: "brainstorm",
    targetMarket: "Digital nomads, expats, location-independent workers",
    tam: "€2B tax advisory market",
    pricing: "€29/mo SaaS",
    stack: ["Multi-jurisdictional tax rules", "Optimization engine"],
    effort: "1-month", revenueModel: "Monthly subscription",
    tags: ["tax", "digital-nomad", "international", "compliance"],
  },
  {
    id: 30, name: "AI Pitch Deck Generator", slug: "ai-pitch-deck",
    tagline: "Investor-ready pitch decks in 5 minutes",
    description: "Trained on YC, Sequoia, and a16z standards. Input your startup data, get a professional pitch deck with market sizing, financial projections, and competitive analysis.",
    category: "saas", status: "brainstorm",
    targetMarket: "Founders raising capital",
    tam: "€2B pitch/fundraising tools",
    pricing: "€29 per deck",
    stack: ["AI generation", "Proven deck structures", "PDF/PPTX export"],
    effort: "2-weeks", revenueModel: "Pay-per-use",
    tags: ["fundraising", "pitch", "startup", "investors"],
  },
  {
    id: 31, name: "AI Supply Chain", slug: "ai-supply-chain",
    tagline: "Find cheapest suppliers, negotiate by email, track shipments",
    description: "AI scans Alibaba and supplier databases, compares prices, negotiates via email, and tracks shipments. For e-commerce sellers and dropshippers.",
    category: "vertical", status: "brainstorm",
    targetMarket: "E-commerce sellers, dropshippers",
    tam: "€50B supply chain management",
    pricing: "€99/mo SaaS",
    stack: ["Alibaba scraping", "AI negotiation", "Shipment tracking"],
    effort: "3-months", revenueModel: "Monthly subscription",
    tags: ["supply-chain", "ecommerce", "sourcing", "negotiation"],
  },
  {
    id: 32, name: "AI Personal Trainer", slug: "ai-personal-trainer",
    tagline: "Daily adaptive coaching based on sleep, nutrition, mood",
    description: "Morning voice check-in assesses your state. AI adapts workout, nutrition plan, and recovery based on your biometrics, sleep quality, and mood. Gets smarter over time.",
    category: "consumer", status: "brainstorm",
    targetMarket: "Fitness enthusiasts, performance-minded individuals",
    tam: "€15B fitness app market",
    pricing: "€19/mo SaaS",
    stack: ["Biometric integration", "Adaptive AI coaching", "Voice interface"],
    effort: "3-months", revenueModel: "Monthly subscription",
    tags: ["fitness", "health", "coaching", "voice", "consumer"],
  },
  {
    id: 33, name: "Daily Ads (Vibe Marketer)", slug: "daily-ads",
    tagline: "Daily AI-generated ad creatives for DACH marketers",
    description: "10 marketing skills (Brand Voice, Positioning, Keywords, Lead Magnet, Direct Response, SEO, Newsletter, Email Sequences, Content Atomizer) + daily generated ad creatives. DACH-focused Vibe Marketer clone.",
    category: "saas", status: "copy-adapt",
    targetMarket: "DACH marketing agencies, in-house marketers, solopreneurs",
    tam: "€5B DACH digital marketing",
    pricing: "€149 one-time (skills) + €39-199/mo (Daily Ads SaaS)",
    stack: ["Next.js", "Claude API", "Brand Memory", "Gemini images"],
    effort: "2-weeks", revenueModel: "One-time + subscription",
    tags: ["marketing", "ads", "dach", "content", "copy-adapt"],
  },
  {
    id: 34, name: "IdeaBrowser", slug: "ideabrowser",
    tagline: "1000+ AI business ideas with instant analysis",
    description: "Browse curated business ideas, get AI-powered market analysis, competition check, and revenue projections. Direct integration with Business OS to start building immediately.",
    category: "saas", status: "copy-adapt",
    targetMarket: "Idea hunters, founders, startup enthusiasts",
    tam: "€2B startup tools market",
    pricing: "Free (10 ideas/mo), €19/mo pro (unlimited + AI analysis), €99/mo enterprise",
    stack: ["Next.js", "Neon DB", "Claude API", "BOS integration"],
    effort: "1-week", revenueModel: "Freemium + subscription",
    tags: ["ideas", "founders", "startup", "marketplace", "bos-integration"],
  },
];
